services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pivothire_app
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - default
      - openinary_network

  db:
    image: postgres:15-alpine
    container_name: pivothire_db
    restart: always
    environment:
      POSTGRES_USER: pivothire_user
      POSTGRES_PASSWORD: pivothire_postgresdb_pswd202506
      POSTGRES_DB: pivothire_prod
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pivothire_user -d pivothire_prod"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
  openinary_network:
    name: openinary_default
    external: true